{
 "title": "Netbird / Relay",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(relay_peers,cluster)"
    }
   },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(relay_peers{cluster=\"$cluster\"},environment)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(relay_peers{cluster=\"$cluster\", environment=\"$environment\"},job)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(relay_peers{cluster=\"$cluster\", environment=\"$environment\", job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Core metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "description": "Number of connected peers by host",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "relay_peers{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}",
     "legendFormat": "{{cluster}}/{{environment}}/{{job}}"
    }
   ]
  },
  {
   "title": "Active peers",
   "type": "timeseries",
   "description": "Number of active connected peers by host\n\nIdeally, this number would stay around 20% of the total connections, indicating that most of the connections are P2P",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "relay_peers_active{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}",
     "legendFormat": "{{cluster}}/{{environment}}/{{job}}"
    }
   ]
  },
  {
   "title": "Idle peers",
   "type": "timeseries",
   "description": "Number of idle connected peers by host",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "relay_peers_idle{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}",
     "legendFormat": "{{cluster}}/{{environment}}/{{job}}"
    }
   ]
  },
  {
   "title": "Relay peer authentication latency ",
   "type": "timeseries",
   "description": "Authentication latency faced by each relay peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(relay_peer_authentication_time_milliseconds_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(relay_peer_authentication_time_milliseconds_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(relay_peer_authentication_time_milliseconds_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Relay peer store latency ",
   "type": "timeseries",
   "description": "Time taken for storing each peer connection and metadata into in-memory database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(relay_peer_store_time_milliseconds_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(relay_peer_store_time_milliseconds_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(relay_peer_store_time_milliseconds_bucket{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Relay traffic bandwidth",
   "type": "timeseries",
   "description": "Total number of bytes sent/received to peers ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(relay_transfer_sent_bytes_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(relay_transfer_received_bytes_total{cluster=~\"$cluster\",environment=~\"$environment\",job=~\"$job\"}[$__rate_interval]) *-1",
     "legendFormat": "received"
    }
   ]
  }
 ]
}