{
  lib,
  clan-core,
  config,
  ...
}:

let
  suffix = config.clan.core.vars.generators.disk-id.files.diskId.value;
in
{
  imports = [
    clan-core.clanModules.disk-id
  ];

  # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
  # Otherwise your system might not boot because of missing partitions / filesystems
  boot.loader.grub.efiSupport = lib.mkDefault true;
  boot.loader.grub.efiInstallAsRemovable = lib.mkDefault true;

  disko.devices = {
    disk = {
      "main" = {
        name = "main-" + suffix;
        type = "disk";
        # device = <uuid>;
        content = {
          type = "gpt";
          partitions = {
            "boot" = {
              size = "1M";
              type = "EF02"; # for grub MBR
              priority = 1;
            };
            "ESP" = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "nofail" ];
              };
            };
            "luks" = {
              size = "100%";
              content = {
                type = "luks";
                name = "cryptroot"; # luks name
                # Optionally: add keyFile or clevis if desired
                content = {
                  type = "filesystem";
                  format = "btrfs"; # or btrfs/bcachefs
                  mountpoint = "/";
                };
              };
            };
          };
        };
      };
    };
  };
}
