<?php 
return array (
  'loading_message' => 'Chargement, veuillez patienter...',
  'ui_settings' => 'Sélectionner la qualité du flux',
  'ui_channels' => 'Liste des chaînes',
  'ui_play' => 'Commencer la lecture',
  'ui_stop' => 'Arrêter la lecture',
  'ui_volume_circle' => 'Glisser pour changer le volume',
  'ui_playlists' => 'Écouter dans votre lecteur favori',
  'ui_back' => 'Retour',
  'status_init' => 'Chargement de {STREAM}...',
  'status_playing' => 'Lecture de {STREAM}...',
  'status_stopped' => 'Lecteur arrêté.',
  'status_volume' => 'Volume : {LEVEL}',
  'status_muted' => 'Lecteur muet.',
  'song_history' => 'Historique des chansons',
  'ui_history' => 'Afficher l\'historique des pistes',
  'history_artist_title' => 'Artiste/Titre',
  'history_added' => 'Ajouté',
  'history_hour_ago' => 'h',
  'history_min_ago' => 'min',
  'history_sec_ago' => 'sec',
  'history_just_now' => 'à l\'instant',
  'history_no_history' => 'Aucun historique disponible pour le moment.',
  'share' => 'Partager',
  'twitter_share' => 'J\'écoute {TRACK} !',
  'error' => 'ERREUR',
  'error_defined' => 'AUCUNE CHAÎNE DÉFINIE',
  'error_create' => 'Impossible de trouver des chaînes, veuillez en créer une !',
  'error_invalid' => 'Chaîne invalide !',
  'error_stream' => 'ERREUR : Le flux spécifié ou sélectionné n\'existe pas !',
  'error_network' => 'ERREUR : Une erreur réseau s\'est produite !',
  'error_playback' => 'ERREUR : Échec de la lecture, le chargement du flux a échoué !',
);
