#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat >&2 <<EOF
Usage:
  $0 host <hostname> <option-name>

  $0 home <hostname> <user> <option-name>
EOF
    exit 1
}

VTYPE="${1:-}"
shift || usage

REPO="${HOME}/ghq/github.com/badele/nix-homelab"

case "$VTYPE" in
host)
    if [[ "$#" -ne 2 ]]; then
        usage
    fi

    VHOSTNAME="$1"
    VOPTION_NAME="$2"
    ATTR="nixosConfigurations.${VHOSTNAME}.config.${VOPTION_NAME}"
    ;;

home)
    if [[ "$#" -ne 3 ]]; then
        usage
    fi

    VHOSTNAME="$1"
    VUSER="$2"
    VOPTION_NAME="$3"
    ATTR="nixosConfigurations.${VHOSTNAME}.config.home-manager.users.${VUSER}.${VOPTION_NAME}"
    ;;

*)
    usage
    ;;
esac

printf ':p %s\n' "$ATTR" |
    nix --quiet repl --expr "builtins.getFlake \"${REPO}\""
