{
  lib,
  ...
}:
let
  deviceId = "/dev/disk/by-id/wwn-0x5000000000000314";
  diskId = "7520589418904802b6808b7661df4976";
in
{
  # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
  # Otherwise your system might not boot because of missing partitions / filesystems
  boot.loader.grub.efiSupport = lib.mkDefault true;
  boot.loader.grub.efiInstallAsRemovable = lib.mkDefault true;

  disko.devices = {
    disk = {
      "main" = {
        name = "main-${diskId}";
        type = "disk";
        device = deviceId;

        # device = <uuid>;
        content = {
          type = "gpt";
          partitions = {
            "boot" = {
              size = "1M";
              type = "EF02"; # for grub MBR
              priority = 1;
            };
            "ESP" = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "nofail" ];
              };
            };
            "luks" = {
              size = "100%";
              content = {
                type = "luks";
                name = "cryptroot"; # luks name
                # Optionally: add keyFile or clevis if desired
                content = {
                  type = "filesystem";
                  format = "btrfs"; # or btrfs/bcachefs
                  mountpoint = "/";
                };
              };
            };
          };
        };
      };
    };
  };
}
