#!/usr/bin/env bash

# Vars
volvalue=5
timeout=3000
pulseid=$(pgrep pulseaudio)
activesink=$(pactl list short sinks | grep RUNNING | awk '{ print $1}')

# Send notification
function notify {
    muted=$(pulsemixer --id "$1" --get-mute)
    volume=$(pulsemixer --id "$1" --get-volume | awk '{print $1}')
    bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')

    # Search font symbol => https://www.nerdfonts.com/cheat-sheet
    if [ "$muted" -ne 1 ]; then
        if [ "$volume" -lt 34 ]; then
            icon="󰕿"
        elif [ "$volume" -lt 67 ]; then
            icon="󰖀"
        elif [ "$volume" -le 100 ]; then
            icon="󰕾"
        else
            icon="󱄡"
        fi
        dunstify -u low -r "$pulseid" -t "$timeout" "$icon $bar"
    else
        # icon="status/audio-volume-muted-symbolic.svg"
        dunstify -u low -r "$pulseid" -t "$timeout" "󰝟 muted"
    fi
}

# Update volume
mix() {
    unmute=""
    if [[ "$(pulsemixer --get-mute)" == "1" ]]; then
        unmute="--toggle-mute"
    fi

    case $1 in
    up)
        pulsemixer $unmute --change-volume +"$volvalue" --id "$2"
        ;;
    down)
        pulsemixer $unmute --change-volume -"$volvalue" --id "$2"
        ;;
    mute)
        pulsemixer --toggle-mute --id "$2"
        ;;
    esac

    notify "$2"
}

# Select source
case $1 in
output)
    mix "$2" "$activesink"
    ;;
mic)
    mix "$2" "source-1"
    ;;
esac
